<html xmlns:string="xalan://java.lang.String" xmlns:lxslt="http://xml.apache.org/xslt">
<head>
<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Unit Test Results: All Tests</title>
<link rel="stylesheet" type="text/css" title="Style" href="stylesheet.css">
</head>
<body onload="open('allclasses-frame.html','classListFrame')">
<h1>Unit Test Results.</h1>
<table width="100%">
<tr>
<td align="left"></td><td align="right">Designed for use with <a href="http://www.junit.org/">JUnit</a> and <a href="http://ant.apache.org/">Ant</a>.</td>
</tr>
</table>
<hr size="1">
<h2>All Tests</h2>
<table class="details" border="0" cellpadding="5" cellspacing="2" width="95%">
<tr valign="top">
<th>Class</th><th>Name</th><th>Status</th><th width="80%">Type</th><th nowrap>Time(s)</th>
</tr>
<tr valign="top" class="Error">
<td><a href="appname/bl/dao/0_BookDaoQueryAllTest.html">BookDaoQueryAllTest</a></td><td><a name="queryAll_test001"></a><a href="appname/bl/dao/0_BookDaoQueryAllTest.html#queryAll_test001">queryAll_test001</a></td><td>Error</td><td>Could not open JDBC Connection for transaction; nested exception is org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.ConnectException: Connection refused: connect: localhost" [90067-196]<br>
<br>
<code>org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.ConnectException: Connection refused: connect: localhost" [90067-196]<br>	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:289)<br>	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:377)<br>	at org.springframework.test.context.transaction.TransactionContext.startTransaction(TransactionContext.java:102)<br>	at org.springframework.test.context.transaction.TransactionalTestExecutionListener.beforeTestMethod(TransactionalTestExecutionListener.java:200)<br>	at org.springframework.test.context.TestContextManager.beforeTestMethod(TestContextManager.java:269)<br>	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)<br>	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)<br>	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)<br>	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)<br>	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)<br>	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)<br>	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)<br>	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)<br>Caused by: org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.ConnectException: Connection refused: connect: localhost" [90067-196]<br>	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)<br>	at org.h2.message.DbException.get(DbException.java:168)<br>	at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:457)<br>	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:334)<br>	at org.h2.jdbc.JdbcConnection.&lt;init&gt;(JdbcConnection.java:116)<br>	at org.h2.jdbc.JdbcConnection.&lt;init&gt;(JdbcConnection.java:100)<br>	at org.h2.Driver.connect(Driver.java:69)<br>	at java.sql.DriverManager.getConnection(DriverManager.java:664)<br>	at java.sql.DriverManager.getConnection(DriverManager.java:208)<br>	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:153)<br>	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:144)<br>	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:196)<br>	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:159)<br>	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:246)<br>Caused by: java.net.ConnectException: Connection refused: connect<br>	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)<br>	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)<br>	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)<br>	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)<br>	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)<br>	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)<br>	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)<br>	at java.net.Socket.connect(Socket.java:589)<br>	at org.h2.util.NetUtils.createSocket(NetUtils.java:103)<br>	at org.h2.util.NetUtils.createSocket(NetUtils.java:83)<br>	at org.h2.engine.SessionRemote.initTransfer(SessionRemote.java:115)<br>	at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:453)<br>
</code></td><td>2.167</td>
</tr>
<tr valign="top" class="TableRowColor">
<td><a href="appname/bl/service/1_BookServiceTest.html">BookServiceTest</a></td><td><a name="getList_test001"></a><a href="appname/bl/service/1_BookServiceTest.html#getList_test001">getList_test001</a></td><td>Success</td><td></td><td>0.007</td>
</tr>
<tr valign="top" class="Error">
<td><a href="appname/web/2_BookControllerTest.html">BookControllerTest</a></td><td><a name="list_test001"></a><a href="appname/web/2_BookControllerTest.html#list_test001">list_test001</a></td><td>Error</td><td>javax.servlet.http.HttpServletRequest.getAsyncContext()Ljavax/servlet/AsyncContext;<br>
<br>
<code>java.lang.NoSuchMethodError: javax.servlet.http.HttpServletRequest.getAsyncContext()Ljavax/servlet/AsyncContext;<br>	at org.springframework.test.web.servlet.TestDispatcherServlet.service(TestDispatcherServlet.java:73)<br>	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)<br>	at org.springframework.mock.web.MockFilterChain$ServletFilterProxy.doFilter(MockFilterChain.java:160)<br>	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:127)<br>	at org.springframework.test.web.servlet.MockMvc.perform(MockMvc.java:151)<br>	at appname.web.BookControllerTest.list_test001(BookControllerTest.java:82)<br>	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)<br>	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)<br>	at org.mockito.internal.junit.JUnitRule$1.evaluateSafely(JUnitRule.java:66)<br>	at org.mockito.internal.junit.JUnitRule$1.evaluate(JUnitRule.java:46)<br>	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)<br>	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)<br>	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)<br>	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)<br>	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)<br>	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)<br>
</code></td><td>0.551</td>
</tr>
</table>
</body>
</html>
